### ISSUE TITLE
"list <namespace>" command does not work

### ISSUE THREAD

**Issue by gmdmi** [yiisoft/yii-console#168]
For example `./yii list debug`:
```
2023-02-10 13:23:45.064400 [error][application] Symfony\Component\Console\Exception\NamespaceNotFoundException: There are no commands defined in the "debug" namespace. in /var/www/app/vendor/symfony/console/Application.php:632 while running console command "list".

Message context:

exception: Symfony\Component\Console\Exception\NamespaceNotFoundException: There are no commands defined in the "debug" namespace. in /var/www/app/vendor/symfony/console/Application.php:632
Stack trace:
#0 /var/www/app/vendor/symfony/console/Descriptor/ApplicationDescription.php(87): Symfony\Component\Console\Application->findNamespace('debug')
#1 /var/www/app/vendor/symfony/console/Descriptor/ApplicationDescription.php(64): Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication()
#2 /var/www/app/vendor/symfony/console/Descriptor/TextDescriptor.php(185): Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands()
#3 /var/www/app/vendor/symfony/console/Descriptor/Descriptor.php(43): Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication(Object(Yiisoft\Yii\Console\Application), Array)
#4 /var/www/app/vendor/symfony/console/Helper/DescriptorHelper.php(65): Symfony\Component\Console\Descriptor\Descriptor->describe(Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput), Object(Yiisoft\Yii\Console\Application), Array)
#5 /var/www/app/vendor/symfony/console/Command/ListCommand.php(71): Symfony\Component\Console\Helper\DescriptorHelper->describe(Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput), Object(Yiisoft\Yii\Console\Application), Array)
#6 /var/www/app/vendor/symfony/console/Command/Command.php(312): Symfony\Component\Console\Command\ListCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput))
#7 /var/www/app/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput))
#8 /var/www/app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\ListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput))
#9 /var/www/app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput))
#10 /var/www/app/vendor/yiisoft/yii-runner-console/src/ConsoleApplicationRunner.php(62): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Yiisoft\Yii\Console\Output\ConsoleBufferedOutput))
#11 /var/www/app/yii(11): Yiisoft\Yii\Runner\Console\ConsoleApplicationRunner->run()
#12 {main}
time: 1676035425.064434
memory: 5885920
category: 'application'
```

**Comment by vjik** [comment]
Closed by https://github.com/yiisoft/yii-console/pull/170
